#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          MDS-Startup
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Minecraft Development Server Startup Service
### END INIT INFO

/root/auto_script.sh
